algoritmo "Ex42CursoEmVideo"
var
      n, c : inteiro
inicio
      c <- 0
       Escreval("Contador á sua escolha")
       Escreval("----------------------")
       Escreva("Digite um número positivo para fazer a contagem até ele : ")
       Leia(n)
       n <- n + 1
       Enquanto (c < n) faca
                Escreva(" ", c, " ")
                c <- c + 1
       FimEnquanto
       
fimalgoritmo