algoritmo "Ex4CursoemVideo"
var
   n1, n2, s : inteiro
inicio
      Escreval("Calculadora de dois número inteiros")
      Escreval("-----------------------------------")
      Escreva("Digite o primeiro número ")
      Leia(n1)
      Escreva("Digite o segundo número ")
      Leia(n2)
      s <- n1 + n2
      Escreval("A soma dos dois números escritos : ", n1, " e ", n2, " resulta no total de ", s)
fimalgoritmo