algoritmo "Ex88CursoEmVideo"
var
a, b : inteiro
Procedimento Gerador(A,B: inteiro)
Inicio
a <- 0
b <- 4
   Escreval("-----------------------")
   Enquanto (a < b) faca
            Escreval("  A P R E N D E N D O  ")
            eSCREVAL("    P O R T U G O L    ")
            Escreval()
            a <- a + 1
   FimEnquanto
   eSCREVAL("-----------------------")
FimProcedimento
inicio
    Gerador(b,a)
fimalgoritmo