algoritmo "Ex90CursoEmVideo"
var
x, y, c : inteiro
Procedimento Somador()
inicio
    c <- x + y
    Escreval("A soma de ", x, " e ", y, " é ", c)
FimProcedimento
inicio
    Escreval("Soma de dois valores á sua escolha.")
    Escreval("-----------------------------------")
    Escreval()
    Escreva("Digite o 1º valor : ")
    Leia(x)
    Escreva("Digite o 2º valor : ")
    Leia(y)
    Somador()
fimalgoritmo