algoritmo "Ex95CursoEmVideo"
var
n1, n2, s : inteiro
Funcao soma(A, B: inteiro): inteiro
inicio
      Retorne A + B
FimFuncao

inicio
      Escreval("SOMANDO 2 NÚMEROS COM FUNÇÃO")
      Escreval("----------------------------")
      Escreval()
      Escreva("Digite o 1º número : ")
      Leia(n1)
      Escreva("Digite o 2º número : ")
      Leia(n2)
      s <- soma(n1,n2)
       Escreval("A soma entre ", n1, " e ", n2, " é ", s)
fimalgoritmo